version: '3.8'

services:
  fiapcloudgames:
    image: postgres:15-alpine
    container_name: fcg-fiapcloudgames
    environment:
      POSTGRES_USER: fcg_user
      POSTGRES_PASSWORD: fcg_password
      POSTGRES_DB: fcg_main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fcg_user -d fcg_main"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fcg-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: fcg-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: fcg_user
      RABBITMQ_DEFAULT_PASS: fcg_password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fcg-network

  redis:
    image: redis:7-alpine
    container_name: fcg-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fcg-network

  users:
    image: igoranthony12/users-api:latest
    container_name: fcg-users
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=fiapcloudgames;Database=users;Username=fcg_user;Password=fcg_password
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=fcg_user
      - RabbitMQ__Password=fcg_password
      - RabbitMQ__VirtualHost=/
      - Jwt__Key=minha_chave_secreta_super_segura_de_desenvolvimento_com_mais_de_32_caracteres_12345
    depends_on:
      fiapcloudgames:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - fcg-network

  catalog-worker-service:
    image: drungas/fcgcatalogworker:latest
    container_name: fcg-catalog-worker-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=fiapcloudgames;Database=catalog;Username=fcg_user;Password=fcg_password
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=fcg_user
      - RabbitMQ__Password=fcg_password
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__KeyQueuePaymentProcessed=payment.processed
    depends_on:
      fiapcloudgames:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - fcg-network

  catalog:
    image: devsergioh/fcg-catalog-api:1.0.0
    container_name: fcg-catalog
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=fiapcloudgames;Database=catalog;Username=fcg_user;Password=fcg_password
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=fcg_user
      - RabbitMQ__Password=fcg_password
      - RabbitMQ__VirtualHost=/
      - "Redis__ConnectionString=redis:6379"
      - "Redis__InstanceName=fcg:catalog:"
      - Redis__DefaultTtlMinutes=15
      - Jwt__SigningKey=minha_chave_secreta_super_segura_de_desenvolvimento_com_mais_de_32_caracteres_12345
    depends_on:
      fiapcloudgames:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - fcg-network

  payments:
    image: drungas/fcgpayments:latest
    container_name: fcg-payments
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=fiapcloudgames;Database=payments;Username=fcg_user;Password=fcg_password
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__Username=fcg_user
      - RabbitMQ__Password=fcg_password
      - RabbitMQ__KeyQueueOrderPlaced=order_placed
      - RabbitMQ__KeyPublisher=payment.processed
    depends_on:
      fiapcloudgames:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - fcg-network

  notifications:
    image: igoranthony12/notification-api:latest
    container_name: fcg-notifications
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=fiapcloudgames;Database=notifications;Username=fcg_user;Password=fcg_password
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=fcg_user
      - RabbitMQ__Password=fcg_password
      - RabbitMQ__VirtualHost=/
      - Smtp__Host=smtp.gmail.com
      - Smtp__Port=587
      - Smtp__Username=exemplo@email
      - Smtp__Password=exemplopassword
      - Smtp__SenderName=Fiap Cloud Games
      - Smtp__SenderEmail=exemplo@email
    depends_on:
      fiapcloudgames:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - fcg-network

volumes:
  postgres_data:

networks:
  fcg-network:
    driver: bridge
