_format_version: "3.0"
_transform: false
consumers:
- custom_id: fcgames-api
  jwt_secrets:
  - algorithm: HS256
    key: FCGames
    secret: ChaveSuperSecretaECompridaDeExemplo123!
  username: fcgames-api
services:
- connect_timeout: 60000
  enabled: true
  host: host.docker.internal
  name: catalog-service
  port: 8082
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - POST
    - PUT
    - DELETE
    name: catalog-service-category-no-public
    path_handling: v1
    paths:
    - ~/catalog-service/(api/Category(?:/[0-9]+)?)$
    plugins:
    - config:
        anonymous: null
        claims_to_verify:
        - exp
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        run_on_preflight: true
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - catalog
    - category
  - https_redirect_status_code: 426
    methods:
    - GET
    name: catalog-service-category-public
    path_handling: v1
    paths:
    - ~/catalog-service/(api/Category(?:/[0-9]+)?)$
    plugins:
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - category
    - catalog
  - https_redirect_status_code: 426
    methods:
    - POST
    - PUT
    - DELETE
    name: catalog-service-game-no-public
    path_handling: v1
    paths:
    - ~/catalog-service/(api/Game(?:/[0-9]+)?)$
    plugins:
    - config:
        anonymous: null
        claims_to_verify:
        - exp
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        run_on_preflight: true
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - game
    - catalog
  - https_redirect_status_code: 426
    methods:
    - POST
    name: catalog-service-game-order-no-public
    path_handling: v1
    paths:
    - ~/catalog-service/(api/GameOrders(?:/[0-9]+)?)$
    plugins:
    - config:
        anonymous: null
        claims_to_verify:
        - exp
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        run_on_preflight: true
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - catalog
    - game-order
  - https_redirect_status_code: 426
    methods:
    - GET
    name: catalog-service-game-order-public
    path_handling: v1
    paths:
    - ~/catalog-service/(api/GameOrders(?:/[0-9]+)?)$
    plugins:
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - catalog
    - game-order
  - https_redirect_status_code: 426
    methods:
    - GET
    name: catalog-service-game-public
    path_handling: v1
    paths:
    - ~/catalog-service/(api/Game(?:/[0-9]+)?)$
    plugins:
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - game
    - catalog
  - https_redirect_status_code: 426
    methods:
    - GET
    name: catalog-service-health
    path_handling: v1
    paths:
    - ~/catalog-service/(Health)
    plugins:
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - health
    - catalog
  - https_redirect_status_code: 426
    methods:
    - GET
    name: catalog-service-library-no-public
    path_handling: v1
    paths:
    - ~/catalog-service/(api/Library)
    plugins:
    - config:
        anonymous: null
        claims_to_verify:
        - exp
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        run_on_preflight: true
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - library
    - catalog
  - https_redirect_status_code: 426
    methods:
    - GET
    name: catalog-service-metrics
    path_handling: v1
    paths:
    - ~/catalog-service/(metrics)
    plugins:
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - metrics
    - catalog
  - https_redirect_status_code: 426
    methods:
    - POST
    - PUT
    - DELETE
    name: catalog-service-reviews-no-public
    path_handling: v1
    paths:
    - ~/catalog-service/(api/Reviews(?:/[^/]+)*)/?$
    plugins:
    - config:
        anonymous: null
        claims_to_verify:
        - exp
        cookie_names: []
        header_names:
        - authorization
        key_claim_name: iss
        maximum_expiration: 0
        run_on_preflight: true
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - catalog
    - review
  - https_redirect_status_code: 426
    methods:
    - GET
    name: catalog-service-reviews-public
    path_handling: v1
    paths:
    - ~/catalog-service/(api/Reviews(?:/[^/]+)*)/?$
    plugins:
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - catalog
    - review
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: host.docker.internal
  name: users-service
  port: 8081
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - POST
    name: user-service-create-public-user
    path_handling: v1
    paths:
    - ~/user-service/(api/User)$
    plugins:
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - users
  - https_redirect_status_code: 426
    methods:
    - GET
    name: user-service-health
    path_handling: v1
    paths:
    - ~/user-service/(Health)
    plugins:
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - health
    - user
  - https_redirect_status_code: 426
    methods:
    - POST
    name: user-service-login
    path_handling: v1
    paths:
    - ~/user-service/(api/Access.*)
    plugins:
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - login
  - https_redirect_status_code: 426
    methods:
    - GET
    name: user-service-metrics
    path_handling: v1
    paths:
    - ~/user-service/(metrics)
    plugins:
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - user
    - metrics
  - https_redirect_status_code: 426
    methods:
    - POST
    - DELETE
    - PUT
    - GET
    name: user-service-users
    path_handling: v1
    paths:
    - ~/user-service/(api/User/.+)
    plugins:
    - config:
        anonymous: null
        claims_to_verify:
        - exp
        cookie_names: []
        header_names:
        - Authorization
        key_claim_name: iss
        maximum_expiration: 0
        run_on_preflight: true
        secret_is_base64: false
        uri_param_names:
        - jwt
      enabled: true
      name: jwt
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        add:
          body: []
          headers: []
          querystring: []
        append:
          body: []
          headers: []
          querystring: []
        http_method: null
        remove:
          body: []
          headers: []
          querystring: []
        rename:
          body: []
          headers: []
          querystring: []
        replace:
          body: []
          headers: []
          querystring: []
          uri: /$(uri_captures[1])
      enabled: true
      name: request-transformer
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
    tags:
    - users
  write_timeout: 60000
