apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  type: LoadBalancer
  selector:
    app: kong

  ports:
    - name: proxy
      port: 8000
      targetPort: proxy

    - name: proxy-ssl
      port: 8443
      targetPort: proxy-ssl

    - name: admin
      port: 8001
      targetPort: admin

    - name: admin-ssl
      port: 8444
      targetPort: admin-ssl

    - name: manager
      port: 8002
      targetPort: manager

    - name: manager-ssl
      port: 8445
      targetPort: manager-ssl

    - name: kong-3
      port: 8003
      targetPort: kong-3

    - name: kong-4
      port: 8004
      targetPort: kong-4