apiVersion: v1
kind: Service
metadata:
  name: konga
spec:
  type: LoadBalancer
  selector:
    app: konga
  ports:
    - name: http
      port: 1337
      targetPort: http
      protocol: TCP