apiVersion: v1
kind: Service
metadata:
  name: konga
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-inbound-cidrs: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-05b402b2346368283, subnet-036a23c3be3fd551b, subnet-0d8fdafff200b5cab, subnet-00215c26f8227c0a4, subnet-08ff3132f2625d138,  subnet-0f945f49867ce6788

spec:
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
  selector:
    app: konga
  ports:
    - name: http
      port: 1337
      targetPort: http
      protocol: TCP