apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  mongo-username: fcg_user
  mongo-password: fcg_password
  connection-string-catalog: mongodb://fcg_user:fcg_password@mongo:27017/fcg_catalog?authSource=admin
