apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 1Gi