apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  postgres-username: fcg_user
  postgres-password: fcg_password
  connection-string-users: Host=fiapcloudgames;Database=users;Username=fcg_user;Password=fcg_password
  connection-string-catalog: Host=fiapcloudgames;Database=catalog;Username=fcg_user;Password=fcg_password
  connection-string-payments: Host=fiapcloudgames;Database=payments;Username=fcg_user;Password=fcg_password
