name: Pipeline Infra

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
          AWS_REGION: ${{vars.AWS_REGION}}
          CLUSTER_NAME: ${{vars.CLUSTER_NAME}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 
      
      - name: Testar Conexão AWS
        run: |
          aws sts get-caller-identity

      - name: Conectar no cluster
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Testar Conexão com o Cluster
        run: |
          kubectl get nodes
          kubectl get pods -A

      - name: Deploy do FCG-Infra
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
          